Algoritmo "exercicio2_carro"

Var
marca: caractere
ano: inteiro
cor: caractere
numero_portas: inteiro
nome_carro: caractere

Inicio
marca <- "Toyata"
ano <- 1997
cor <- "Vermelho"
numero_portas <- 2
nome_carro <- "Supra"

escreval("----------------Informações do carro--------------")
escreval("Marca do carro: ",marca)
escreval("Nome do carro: ",nome_carro)
escreval("Ano do carro: ",ano)
escreval("Cor do carro: ",cor)
escreval("Numero de portas do carro: ",numero_portas)

Fimalgoritmo