algoritmo "exercicio1_numeromeses"

var
   mes: inteiro

inicio

escreva("Digite um número inteiro de 1 a 12 para o mês correspondente: ")
leia(mes)

se mes = 1 entao
escreval("Janeiro")
senao
se mes = 2 entao
escreval("Fevereiro")
senao
se mes = 3 entao
escreval("Março")
senao
se mes = 4 entao
escreval("Abril")
senao
se mes = 5 entao
escreval("Maio")
senao
se mes = 6 entao
escreval("Junho")
senao
se mes = 7 entao
escreval("Julho")
senao
se mes = 8 entao
escreval("Agosto")
senao
se mes = 9 entao
escreval("Setembro")
senao
se mes = 10 entao
escreval("Outubro")
senao
se mes = 11 entao
escreval("Novembro")
senao
se mes = 12 entao
escreval("Dezembro")
senao
escreval("Valor inválido. Digite um número entre 1 e 12.")
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimse
fimalgoritmo


